name: CI Workflow

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Give execute permission
        run: chmod +x system-info.sh

      - name: Run system-info.sh
        run: ./system-info.sh

      - name: Final message
        run: echo "Week 3 CI successful"
