name: CI Pipeline

on:
  push:

jobs:
  system-info:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Show System Info
        run: |
          uname -a
          hostname
          date

      - name: Success Message
        run: echo "Week 3 CI Successful"
